# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the package module
[package]
disabled = true

# Enable memory module
[memory_usage]
disabled = false
symbol = " "

# Enable status module
[status]
disabled = false
